### ISSUE TITLE
Move MaybeUninit static methods to inherent methods

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/libs-team#123]
# Proposal

## Problem statement

Based on [this comment](https://github.com/rust-lang/rust/issues/63569#issuecomment-586143463), the methods were added when making them inherent impls on arrays wasn't possible. This has presumably been fixed in the intervening years.

## Motivation, use-cases

`bar.foo()` is easier to read than `Namespace::foo(bar)`.

## Solution sketches

https://github.com/rust-lang/rust/pull/103128 https://github.com/rust-lang/rust/pull/103130 https://github.com/rust-lang/rust/pull/103131

**Comment by scottmcm** [comment]
nit: I think you mean "[inherent](https://doc.rust-lang.org/reference/items/implementations.html#inherent-implementations)" not "[extension](http://xion.io/post/code/rust-extension-traits.html)".

But because `MaybeUninit` isn't `Deref`, having these as inherent methods rather than associated functions (like they need to be on `ManuallyDrop`) sounds reasonable to me.

**Comment by SUPERCILEX** [comment]
Yup, thanks!
