### ISSUE TITLE
Add `try_all`, `try_any`, `try_position` and `try_rposition` methods to `Iterator` trait

### ISSUE THREAD

**Issue by rodrigocfd** [rust-lang/libs-team#361]
# Proposal

## Problem statement

Currently there is no simple way to use [`all()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.all), [`any()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.any), [`position()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.position) and [`rposition()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.rposition) if the predicate can fail, returning an [`Err`](https://doc.rust-lang.org/std/result/enum.Result.html#variant.Err).

## Motivating examples or use cases

This proposal came from an [StackOverflow question](https://stackoverflow.com/q/78218651/6923555), which asks for a fallible method for `position()`. The answer is rather convoluted when compared to the simplicity of [`try_for_each()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.try_for_each) versus [`for_each()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.for_each).

The original question is:

```rust
let items: &[Result<&str, u32>] = &[Ok("foo"), Err(444), Ok("bar")];

let bar_idx = items.iter()
    .position(|item| item? == "bar")?; // what to do here?
```

## Solution sketch

I sketched a `FooIterator` with the aforementioned methods so I could use them right away, but I suppose they should be members of [`Iterator`](https://doc.rust-lang.org/std/iter/trait.Iterator.html). Also, I'm aware the implementation below is **far** from being standardized:

```rust
pub trait FooIterator: Iterator {
	fn try_all<E, F>(&mut self, mut predicate: F) -> Result<bool, E>
		where Self: Sized,
			F: FnMut(Self::Item) -> Result<bool, E>,
	{
		for item in self {
			if !predicate(item)? {
				return Ok(false)
			}
		}
		Ok(true)
	}

	fn try_any<E, F>(&mut self, mut predicate: F) -> Result<bool, E>
		where Self: Sized,
			F: FnMut(Self::Item) -> Result<bool, E>,
	{
		for item in self {
			if predicate(item)? {
				return Ok(true)
			}
		}
		Ok(false)
	}

	fn try_position<E, F>(&mut self, mut predicate: F) -> Result<Option<usize>, E>
		where Self: Sized,
			F: FnMut(Self::Item) -> Result<bool, E>,
	{
		for (idx, item) in self.enumerate() {
			if predicate(item)? {
				return Ok(Some(idx));
			}
		}
		Ok(None)
	}

	fn try_rposition<E, F>(&mut self, mut predicate: F) -> Result<Option<usize>, E>
		where Self: Sized + DoubleEndedIterator,
			F: FnMut(Self::Item) -> Result<bool, E>,
	{
		for (idx, item) in self.rev().enumerate() {
			if predicate(item)? {
				return Ok(Some(idx));
			}
		}
		Ok(None)
	}
}

impl<'a, T> TryIterator for core::slice::Iter<'a, T> {}
impl<I> TryIterator for std::iter::Enumerate<I> where I: Iterator {}
impl<I> TryIterator for std::iter::Skip<I> where I: Iterator {}
impl<I> TryIterator for std::iter::StepBy<I> where I: Iterator {}
impl<I> TryIterator for std::iter::Take<I> where I: Iterator {}
```

## Alternatives

I implemented and published the [`TryIterator`](https://crates.io/crates/try-iterator) crate, so I could use these methods immediately. But I believe these methods have their place in the standard library.

**Comment by the8472** [comment]
More general

```rust
let position: Result<usize, _> =  iter.try_and(|it| it.position(|e| e == "bar"));
```

**Comment by shepmaster** [comment]
[`itertools::process_results`](https://docs.rs/itertools/latest/itertools/fn.process_results.html) / [`Itertools::process_results`](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.process_results) are offshoots of the original shunt code that I added to the standard library. Both versions have evolved since then, but presumably still solve the same core issue.

```rust
use itertools::Itertools; // 0.12.1

fn main() {
    let v = [Ok::<u8, ()>(1), Ok(3)]
        .into_iter()
        .process_results(|mut i| i.all(|i| i > 2));
    assert_eq!(Ok(false), v);

    let v = [Ok::<u8, ()>(1), Ok(3)]
        .into_iter()
        .process_results(|mut i| i.position(|i| i > 2));
    assert_eq!(Ok(Some(1)), v);
}
```

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and we are happy to add these. However these should be based on the `Try` trait to allow them to work with both `Option` and `Result`. Additionally, the implementation should use `try_fold` internally since many iterators will specialize that method for better performance. Finally, stabilization of these will likely be blocked on the stabilization of the `Try` trait, like most other methods using that trait.

Feel free to [open a tracking issue](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue%2C+T-libs&template=library_tracking_issue.md&title=Tracking+Issue+for+XXX) and open a PR to rust-lang/rust to add it as an unstable feature.

**Comment by rodrigocfd** [comment]
@Amanieu where I can find information about this `Try` trait?

**Comment by Amanieu** [comment]
Have a look at the existing `try_find` and `try_reduce` methods on the `Iterator` trait.
