### ISSUE TITLE
Add `PathBuf::into_join`

### ISSUE THREAD

**Issue by mo8it** [rust-lang/libs-team#426]
# Proposal

## Problem statement

Calling [`join`](https://doc.rust-lang.org/stable/std/path/struct.Path.html#method.join) on `PathBuf` always allocates a new `PathBuf` instead of trying to reuse the allocation of the existing one.

## Motivating examples or use cases

The following is used too often in the different Rust codebases that I read:

```rust
returns_path_buf().join(path)
```

But I see why people don't want to use `push` in such cases. The equivalent with `push` is much longer because it requires a mutable temporary variable and two additional lines:

```rust
let mut path_buf = returns_path_buf();
path_buf.push(path);
path_buf
```

## Solution sketch

My proposal is to add the following method to `PathBuf`:

```rust
impl PathBuf {
    #[inline]
    pub fn into_join<P: AsRef<Path>>(mut self, path: P) -> Self {
        self.push(path);
        self
    }
}
```

So the example above becomes:

```rust
returns_path_buf().into_join(path)
```

Of course, this could still allocate if the `PathBuf` returned by `returns_path_buf` doesn't have enough capacity. But at least it tries to use any capacity left. It is also possible that the resulted path is even shorter which means that no additional capacity is needed.

`into_join` can of course be chained:

```rust
returns_path_buf().into_join(path1).into_join(path2)
```

We can add a lint to recommend using `into_join` when the `PathBuf` isn't used anywhere afterwards.

## Alternatives

The alternative would be to use the existing `push` method. But it is rarely used because `join` is much more ergonomic as shown in the example above.

## Links and related work

[Related post in the internals forum](https://internals.rust-lang.org/t/into-join-for-pathbuf)

**Comment by the8472** [comment]
We discussed this during today's libs-API meeting. This is an instance of the very general pattern where one wants to chain unit-returning calls (similar requests frequently [come up in internals](https://internals.rust-lang.org/t/vec-append-but-by-value/21029/11?u=the8472)). That issue isn't solved by adding more methods that do the same thing except in a chainable way. Instead language or library additions should be explored to make method chaining more ergonomic.
Additionally some team members also suggested adding a `path!(foo / bar / baz)` macro for path construction as an alternative, though that wasn't unanimous due to an unclear scope.
Lastly, absent a demonstration that that path construction is a limiting factor in an application it seems like a premature optimization. In the cases where it is relevant you can already use the existing `push` method.
