### ISSUE TITLE
[ACP] adding todevice call to std::net

### ISSUE THREAD

**Issue by devnexen** [rust-lang/libs-team#432]
# Proposal

## Problem statement

Giving the possibility, for a socket, to be bound to a particular network interface.

## Motivating examples or use cases

It can serve for filtering purpose, e.g. external incoming requests for eth1 then separate private requests for eth0 ... or based on particular type of services e.g. http only.

[Tracking issue](https://github.com/rust-lang/rust/issues/129182) and [the PR](https://github.com/rust-lang/rust/pull/129172).

**Comment by kennytm** [comment]
regarding the PR already sent

```rust
pub fn todevice(&self) -> io::Result<&CStr>;
pub fn set_todevice(&self, ifrname: &CStr) -> io::Result<()>;
```

1. Why the setter takes a `&CStr` rather than a `&str` or `&OsStr`?
2. As mentioned in the PR the getter cannot just return a reference, it must return an owned type (`CString`/`OsString`/`String`)
3. The socket option is called `SO_BINDTODEVICE`, and "todevice" isn't really the specific term here. IMO it makes more sense to just name the functions `device()`/`set_device()`, or call the setter `bind_to_device()`. For reference, [in `socket2`](https://docs.rs/socket2/0.5.7/src/socket2/sys/unix.rs.html#1884) the functions are named:

    ```rust
    pub fn device(&self) -> io::Result<Option<Vec<u8>>>;
    pub fn bind_device(&self, interface: Option<&[u8]>) -> io::Result<()>;
    ```

    (I'm not sure sure why these aren't showing up in docs.rs)

**Comment by lolbinarycat** [comment]
seconding the concerns about naming.

`todevice` is not ideal for several reasons:
* rust method names are almost always snake_case, this has no word separation, and is harder to read (tode vice? tod ev ice?).
* the verb `to` at the start of a method name is usually reserved for methods that perform some kind of conversion
* the verb `to` could also impl sending packets *to* a device, while this would often be used to filter what packets are recieved *from* a device.

**Comment by devnexen** [comment]
Ok for the naming changes. The setter already returned CString since first feedbacks but will change the rest. Thanks

**Comment by the8472** [comment]
Since binding has to happen on an unconnected/unbound socket we first [need a way to do this in std](https://github.com/rust-lang/libs-team/issues/66#issuecomment-1553224283), which is a bigger story (possibly requiring an RFC) since it means adopting a chunk of the socket2 crate.

So this ACP has to be postponed until that prerequisite is fulfilled.
