### ISSUE TITLE
Implementation of raw_ext, metadata_ext and metadata_ext2 features for Apple WatchOS

### ISSUE THREAD

**Issue by vladimir-ea** [rust-lang/libs-team#75]
# Proposal

## Problem statement

Add support for the `raw_ext`, `metadata_ext` and `metadata_ext2` features for the Apple WatchOS platform.  

## Motivation, use-cases

https://github.com/rust-lang/rust/pull/95243 Added compiler support for Apple WatchOS targets. https://github.com/rust-lang/rust/pull/98101 Adds standard library support for Apple WatchOS. The motivation is to complete support for Apple WatchOS targets by implementing these features, giving parity of support for WatchOS as for other Apple platforms (e.g. iOS). 

## Solution sketches

Implementation for WatchOS will be identical to iOs implementations in the first instance. 

## Links and related work

For iOS implementations of these features see: https://github.com/rust-lang/rust/tree/master/library/std/src/os/ios

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by thomcc** [comment]
It's worth figuring out what we want to do here, since. My suggestion is just that we do what... basically every other platform we currently has does, and define these as they are, even if it means copy-pasting from the existing platforms.

That is, I think the assumption that these are the same as iOS is likely not something we want to make, since iOS and watchOS don't even have the same pointer size (e.g. despite both being aarch64, on watchOS pointers are 32 bits -- it's `arm64_32-apple-watchos).

I'm going to nominate this so that it will get into the API team discussion next week.

**Comment by vladimir-ea** [comment]
https://github.com/rust-lang/rust/pull/99497 has been merged.
