### ISSUE TITLE
thread: adding `current_cpu` call

### ISSUE THREAD

**Issue by devnexen** [rust-lang/libs-team#96]
# Proposal

## Motivation, use-cases

In a multi thread process, it is to return the current running CPU core id where the operating system supports it.

## Links and related work

[thread::current_cpu addition](https://github.com/rust-lang/rust/pull/101382)

**Comment by the8472** [comment]
That motivation needs more detail imo. What is knowing the core-ID useful for? Is it a common enough need that it should be in the standard library? Isn't the ID _immediately_ useless because the thread could get scheduled to another core between the time the value is read and the function returns?

**Comment by cuviper** [comment]
You would probably use this in concert with APIs that pin your threads to specific CPUs. In glibc, that's in `sched.h` with `sched_getcpu` and `sched_get`/`set_affinity`.

I would not add anything like `getcpu` to the standard library unless we also add such affinity APIs.

**Comment by programmerjake** [comment]
imho `current_cpu` is useful even without affinity apis, it can be used for things like lock sharding:
```rust
#[derive(Default, Clone, Debug)]
struct Accumulator {
    counts: HashMap<i32, BigInt>,
}
static LOCK_TABLE: RwLock<Vec<Mutex<Accumulator>>> = RwLock::new(Vec::new());
pub fn accumulate(key: i32, amount: &BigInt) {
    let read_lock = LOCK_TABLE.read();
    let cpu = current_cpu();
    if cpu >= read_lock.len() {
        drop(read_lock);
        let write_lock = LOCK_TABLE.write();
        write_lock.resize_with(cpu + 1, Mutex::default);
        drop(write_lock);
        read_lock = LOCK_TABLE.read();
    }
    let accumulator = (*read_lock)[cpu].lock();
    *accumulator.entry(key).or_default() += amount;
}

pub fn get_accumulated() -> Accumulator {
    let read_lock = LOCK_TABLE.read();
    let retval = Accumulator::default();
    for i in &*read_lock {
        let i = i.lock();
        for (k, v) in &*i {
            *retval.counts.entry(k).or_default() += v;
        }
    }
    retval
}
```

**Comment by thomcc** [comment]
Yeah, this is useful independent of support for thread affinities. Code that wants to reduce contention that shards based on the CPU number will often have lower memory usage than code using thread local data.

That said, in such cases the value is at best a hint as the thread may have been moved to another CPU before the call returns[^1], so unlike thread-local data it can't be used to avoid synchronization, but if the call to get the current CPU is cheap enough and the contention is bad enough, it may be still beneficial for performance.

[^1]: Low level target-specific features such as linux rseqs can be used to avoid this but that obviously is not something std can even consider supporting.

That said, I'm unsure that you want to use this without also needing the maximum value, which is tricky: if we expose a `std::thread::max_cpus()` it would be very easy for users to confuse it with `std::thread::available_parallelism()` (which is different). To be honest, I don't know how we could expose this value in a way that avoids this confusion... (OTOH, Perhaps they're the same often enough that only supporting `available_parallelism` is fine)

This is supported on Darwin-based OSes via `pthread_cpu_number_np`, but only on very recent versions (macOS 11, iOS 14.2, ...). At first this concerned me but honestly people who use these targets tend to have up to date OSes so it's fine. (If we wanted better compatibility there are unstable tricks we could use on old macOS, but they're quite sketchy, even for code that only runs on OSes that are no longer being updated). The max value is easily retrievable with `sysctlbyname("hw.ncpu", ...)`.

All that said, IDK if current CPU number belongs in std. It's a bit niche and comes with several caveat about correct usage. Thread ID is a better option most of the time.

### Tangent: Affinity

Anyway, regarding this needing to be tied to affinity: I disagree. I've used both several times and think they're useful separately. When I've used the current CPU number it's generally been in code that did not touch the thread affinity, and when I've modified the thread affinity, it's not really in code that directly uses the current CPU number (it's usually audio code, benchmarking, etc).

I suppose one relationship is that if you set the thread's affinity to a single CPU, you reduce the chance of hitting the issue where the CPU number changes out from under you. Is that what you mean? I can see this, but I guess I've always treated affinity as a hint rather than something I could rely on. (Perhaps you can rely on it on Linux?)

Anyway, I have concerns about exposing thread affinity in that manner on Darwin-based OSes. Darwin has a thread affinity API (`thread_policy_set` with `THREAD_AFFINITY_POLICY`) that can be used in many similar cases, but it basically is just a hint to the scheduler that a certain group of threads will use the same resources and should be scheduled on the same cores (or rather, on cores that share L2 caches). You provide it an abstracted integer tag and threads with the same tag will get scheduled on the same cores.

In practice if you really need pinning to a specific CPU, there are unstable ways to achieve it but even those are still just hints, and we couldn't use them from std anyway.

So... it's really 100% a separate thing on Darwin OSes from CPU numbering, and it sounds hard to add a cross-platform API for this. (Also on Darwin you really should use QOS instead, but that's another story)

**Comment by the8472** [comment]
> Yeah, this is useful independent of support for thread affinities. At high thread counts, code that reduces contention by sharding based on the CPU number will have lower memory usage than code which does the same the same using thread local data.

You could use `thread id % cpu count` or `% shard count` for similar effects if you don't need the true core number, which you don't if you don't have affinities.

**Comment by thomcc** [comment]
You can, but it won’t do as good of a job. Still, I think it’s likely to be good enough that it strongly discourages doing something else in std given the caveats.

**Comment by cuviper** [comment]
> That said, I'm unsure that you want to use this without also needing the maximum value, which is tricky: if we expose a `std::thread::max_cpus()` it would be very easy for users to confuse it with `std::thread::available_parallelism()` (which is different).

Right, it's important to realize that the CPU number does **not** have to be in `0..available_parallelism()`, e.g. if you're pinned to exactly one CPU that isn't 0.

There are also crazier features like [CPU hotplug](https://www.kernel.org/doc/html/latest/core-api/cpu_hotplug.html), which we don't account for at all, although I don't remember if that affects the available CPUs for existing processes.

**Comment by the8472** [comment]
We discussed this in today's libs meeting.

While this method is useful for low-level code (e.g. to avoid cache lines bouncing) it doesn't fit well in the standard library because it's not consistent with `available_parallelism` or thread ids.
And one will likely need a bunch of other platform-specifc methods too like getting the number of physical or logical cores, thread affinities and what-not.

It's niche enough that it can live in an external library.

**Comment by devnexen** [comment]
understood, thanks for having considered it.

**Comment by programmerjake** [comment]
what about having it return a opaque type with `Hash + Eq`? that way it's obvious it can be used for table lookups via `Hash` but the returned values don't have any particular properties other than being different for different cpus.

**Comment by the8472** [comment]
the thread id can serve as a crude approximation, if crude is all you need. if finer control is needed then more platform-specific functions will be necessary anyway.
