### ISSUE TITLE
Deprecate and rename native-endian functions

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/libs-team#99]
# Proposal

## Problem statement

In Rust we use three abbreviations for endianness: We use LE for little-endian, BE for big-endian, and NE for native-endian ("the endianness of the system we are running on"). Unfortunately, "NE" is confusing with "network endian", a very common term used in these contexts.

## Motivation, use-cases

For example, we have [`i8::from_be_bytes()`](https://doc.rust-lang.org/stable/std/primitive.i8.html#method.from_be_bytes), [`i8::from_le_bytes()`](https://doc.rust-lang.org/stable/std/primitive.i8.html#method.from_le_bytes), and [`i8::from_ne_bytes()`](https://doc.rust-lang.org/stable/std/primitive.i8.html#method.from_ne_bytes).

This is pretty nice and consistent, however the "NE" acronym is a little confusing. One major use case of functions that are endianness-sensitive is networking, and in that context the terms "network endian" and "host endian" are often used. "network endian" is always "big endian", and "host endian" has the same connotation as "native endian".

As such it feels like a major footgun to have a function for "native endianness" that is very confusable with "network endianness", especially since there aren't that many use cases for this function _outside_ of networking[^1].

@bluejekyll already hit this problem in trust-dns and I suspect that's not the only time this has confused networky people.

## Solution sketches

I wonder if we should be expanding the acronym here, it feels fine to have people call `from_native_endian_bytes()` here. We can deprecate the existing function to push people in the right direction. I don't think we get much from the NE functions being consistent with BE/LE, if anything the cases where you need BE/LE are places you absolutely do not want to accidentally put NE instead.

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by the8472** [comment]
This is surprising because it says this in the first line

> Create an integer value from its memory representation as a byte array in _native endianness_.

So any IDE auto-complete tool should show this text, even if it gets truncated at some point. So how can one find this method but miss that bit? If we know the process leading to that point then maybe that can be fixed instead.

Deprecating a method because people don't read documentation seems like a bad precedent to me.

**Comment by sfackler** [comment]
We have already deprecated many methods that we have decided were poorly named, even if the documentation was more correct about their behavior.

**Comment by Manishearth** [comment]
> So any IDE auto-complete tool should show this text, even if it gets truncated at some point. So how can one find this method but miss that bit? If we know the process leading to that point then maybe that can be fixed instead.

I am strongly against designing APIs primarily assuming people use IDEs since not all environments can use IDEs.

I do think that it is reasonable to expect users to read the documentation at times; however this is one of those cases where a user may just think the function's purpose is obvious from the name, and these functions have very similar docs so you might read one and think you understand the rest.

**Comment by the8472** [comment]
I mean if people *don't* use an IDE they must be following some other process to discover the API. The sourcecode doesn't materialize from nowhere. My point is that something is encouraging the to use methods without even reading reading the first line of documentation. That process needs to be fixed.

Another suspect I have is opening rustdoc with documentation collapsed:

![image](https://user-images.githubusercontent.com/1065730/188945144-397f3751-3cdb-4224-91b5-4d2afe41642b.png)

Compare javadocs which never hides the summary, even in the compact representation:

![image](https://user-images.githubusercontent.com/1065730/188945480-c9a0c2e8-2c9a-46e6-86a2-135c5be6e068.png)

**Comment by the8472** [comment]
> so looking at the docs it's easy to mistakenly see n*t*** as network and move on.

Renaming the method wouldn't solve that though?

**Comment by Manishearth** [comment]
> I mean if people _don't_ use an IDE they must be following some other process to discover the API. The sourcecode doesn't materialize from nowhere. My point is that something is encouraging them to use methods without even reading the first line of documentation. That process needs to be fixed.

Yes, and seeing a triplet of "be, le, ne" functions might be sufficient to people primed with expectations from other fields. They may just read the docs for one of them. Renaming `ne` to not match that pattern is precisely the fix I'm proposing!

The cold truth of the matter is that people do not read the docs for every API they use. This is not something to "fix", this is just how people code, it would be tons of work to read the docs for _every_ API you're calling. People rely on conventions and expectations quite a bit, and talking about it here isn't going to change that.


And part of the issue here is that these functions, whose _primary use_ is a particular domain, have meanings counter to the conventions of that domain.


(Also, not all IDEs show docs on autocomplete. We really should not be assuming too much about IDE UX when designing APIs)

**Comment by Manishearth** [comment]
> Renaming the method to `from_native_endian_bytes` wouldn't solve that particular quirk though? Maybe `from_host_endian_bytes`? which would be in line with the `h` in hton?

Yeah, that's a good point!

**Comment by the8472** [comment]
> Also, not all IDEs show docs on autocomplete.

Imo this is a bug if it causes developers to materialize some assumed documentation out of thin air and then coding based on those assumptions. Sort of adjacent to Hyrum's law?

> The cold truth of the matter is that people do not read the docs for every API they use. 

And people also transmute repr(Rust) things with private fields. I know we can't prevent it, but we can at least try to discourage it and do whatever is reasonable so that they're not tempted to.

Imo making sure that documentation is not hidden from users is a better outcome than having recurring issues like this. Teach a man to ~fish~ read documentation vs. give him a ~fish~ one more verbose function name.

**Comment by bluejekyll** [comment]
> > so looking at the docs it's easy to mistakenly see `n*t***` as `network` and move on.
> 
> Renaming the method to `from_native_endian_bytes` wouldn't solve that particular quirk though? Maybe `from_host_endian_bytes`? which would be in line with the `h` in hton?

I don't think that's as true as it being buried in the docs. When looking at the method name, it would be far more difficult to miss, as you see it all the time. The docs on the other hand are something you generally (even with an IDE) have to actively open in some manner.

I do think improving the names will help improve the situation. As is, the name is not clear about its intent.

To truly fix this problem, we really need a different set of types, but that's outside the scope of this issue.

**Comment by jkugelman** [comment]
Spelling out this one variation seems odd. How about `from_he_bytes`?

**Comment by programmerjake** [comment]
> Spelling out this one variation seems odd. How about `from_he_bytes`?

assuming `he` means host endian, imho `te` for target endian is what you actually want, because you could be compiling for a big-endian target from a little-endian host or vise versa.

**Comment by programmerjake** [comment]
> > Spelling out this one variation seems odd. How about `from_he_bytes`?
> 
> assuming `he` means host endian, imho `te` for target endian is what you actually want, because you could be compiling for a big-endian target from a little-endian host or vise versa.

or maybe just drop `ne` all together and end up with `from_bytes`/`to_bytes`

**Comment by bluejekyll** [comment]
> or maybe just drop ne all together and end up with from_bytes/to_bytes

Personally, I think this would be a great solution.

**Comment by the8472** [comment]
> from_bytes/to_bytes

I find having a reminder that they're endianness-dependent helpful, dropping that is a bad idea imo.

**Comment by scottmcm** [comment]
I definitely think it's important that the non-portable one *not* have the shortest name.

**Comment by m-ou-se** [comment]
This was discussed briefly in a recent libs-api meeting. The sentiment was that, while the naming is unfortunate and we'd probably prefer something else if we were adding these functions today, it seems like it's not worth changing/deprecating these functions. They're widely used (in over 800 different crates on crates.io), so it'd cause a lot of churn.

**Comment by Manishearth** [comment]
I don't actually think older crates have to stop using these to get the benefit; we can simply _deprecate_ now and let people migrate at leisure, with no planned removal in the near future.

The point would be to get new users to stop using the API.

Clippy adds new warnings all the time and the ecosystem slowly migrates, this wouldn't be that different. I don't think warning churn is a huge deal.

I think warning churn is a big deal in the future-incompat case where we _force_ people to migrate before a particular rust version, but we don't need to do that here.

Overall I find it strange that "warning churn" is considered a problem at all given the widespread use of clippy. People are opting in to warning churn that is far far more churny than this.

**Comment by BurntSushi** [comment]
> I don't think warning churn is a huge deal.

**Comment by BurntSushi** [comment]
@Manishearth 

> I don't think warning churn is a huge deal.

I agree generally for any one particular case, but I do actually think it becomes a huge deal when we start doing it a lot, and especially so for very commonly used routines. I've been on the receiving end of this (even without using Clippy) and it is really quite annoying to deal with. I've long advocated that we consider "bundling" our deprecations, for example, and drop them all at once so that we don't let them trickle out piecemeal. But we don't have any processes in place for that (nor a consensus that we _should_ bundle them).

The other problem I tend to have with changes like this is that there is a big body of code out there using these native endian functions that will likely never get migrated. (Think blog posts, StackOverflow, GitHub issues, etc.) People stumble upon these things, copy the approach and then get a warning that they're using a whole bunch of deprecated routines. Of course, this can't be a strong concern because it would effectively argue against changing anything (not just deprecations), but it is something I do personally think about as part of "churn" and weigh it negatively for changes like this.

I experience this outside of the Rust ecosystem too, and it informs my own internal calculus for whether changes like this are worth doing. There have been oodles of times where I've gone off and used something, invested energy into learning it, figured out how to apply, starting coding it up and then only later learned that the entire approach had been deprecated in favor of something else. _If only_ I had paid attentions to the proper channels, I might have saved myself the effort (and you better believe I do try to head those things off nowadays because I've suffered the costs of that mistake). I do acknowledge that a simple function rename doesn't lend itself to wasting tons of time on its own. What I mean to convey here is my belief that deprecations can simultaneously improve the onboarding experience while also detracting from it.

I wasn't at the libs-api meeting, but yeah, I do acknowledge that the naming of the native endian routines is somewhat unfortunate, and that if we could go back and do it again, it would have been wise to select a different name. But I'm just not sure that this is enough of a problem to justify spraying warnings to some significant chunk of extant Rust crates.

One hypothetical thing that would mitigate some of my concerns would be to soft-deprecate, and then hard-deprecate at an edition boundary and have `cargo fix` rename the routines for you. I don't mean to say that that is what we have to do, but rather, to put forward one possible path forward here. (As I said, it doesn't mitigate all my concerns. It doesn't do anything about code that is no longer being updated but still being read.)

**Comment by Manishearth** [comment]
I think that's a good path to explore.

> But that's an opt-**in**. Deprecations warn by default, and we don't want folks to broadly opt-**out** because we're too noisy.

I understand, I just used that to illustrate that the scale of "800+ crates" isn't actually that big.

**Comment by joshtriplett** [comment]
The conclusion from the meeting referenced in https://github.com/rust-lang/libs-team/issues/99#issuecomment-1282292019 is still true. These names seem *unfortunate* but the churn and the *divergence* between old and new Rust would be painful.
